"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o8$3fsm3f-__445+h-_%n8(9!(v+#w)s7(rpuxp=xo-fe%2=)4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sceneswitcher'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,'/static/')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]

TEMPLATE_DIR = os.path.join(BASE_DIR,"templates")
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'sceneswitcher.UserProfile'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/app'
LOGIN_URL = '/login'


STRIPE_REDIRECT_DOMAIN = 'http://0.0.0.0:7669'
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 # 24 hours
# DOMAIN = "https://sceneswitcher.io/"
# DOMAIN = "http://153.92.208.98:7669"

DOMAIN = 'http://localhost:8000'
STRIPE_SECRET_KEY = 'sk_test_51Q8kbqDIxyydhKbNHtnDPnkAD2akATywXOY3K7HTaw3b4AM8JWjscTxjKEQSt23jJkzjRP3LFAWXZHnlE6ruuc5t00QsVGhNr9'
STRIPE_WEBHOOK_SECRET = 'whsec_28a947a99fc11d931ed7d9f5eff9297d17509c71a8e88c9da29aa21a78b13ea3'
BASIC_PRICE_ID = "price_1Q8mmPDIxyydhKbNiwjoDP8K"
PROFESSIONAL_PRICE_ID = "price_1Q8mn5DIxyydhKbNwls3oJ6J"
PREMIUM_PRICE_ID = "price_1Q8mnXDIxyydhKbNkW1cDSOk"
CUSTOM_PRICE_ID = "price_1Q90tRDIxyydhKbNPkhlEYId"

# ### PRODUCTION KEYS
# STRIPE_SECRET_KEY = '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'
# STRIPE_WEBHOOK_SECRET = 'we_1Q9uKPEt5xiNvM25I66lpa4B'
# BASIC_PRICE_ID = "price_1PyLMBEt5xiNvM25aUUdSFsC"
# PROFESSIONAL_PRICE_ID = "price_1PydW5Et5xiNvM25BQWh5IZ9"
# PREMIUM_PRICE_ID = "price_1PydXLEt5xiNvM25apEAQfaK"
# CUSTOM_PRICE_ID = "price_1Q9u8rEt5xiNvM25sDUuYNSG"

# ### TEST KEYS
# STRIPE_SECRET_KEY = 'sk_test_51PxpLrEt5xiNvM25bIRFusvXNrEWwgFee9uMPzhFsJkKNerUk8M9XqwTjTJyMbqsjtySGMRej10S6RwCbrsrdGxN00nsGkkaDw'
# STRIPE_WEBHOOK_SECRET = 'whsec_rNWc0OPfSjz5YGvd3LTNYWgYOgmL69kP'
# BASIC_PRICE_ID = "price_1QC6faEt5xiNvM2503VDSofn"
# PROFESSIONAL_PRICE_ID = "price_1QC6gUEt5xiNvM25ouuuCwkV"
# PREMIUM_PRICE_ID = "price_1QC6hZEt5xiNvM25RpVAnpDd"
# CUSTOM_PRICE_ID = ""


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER = 'support@sceneswitcher.io'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = 'dpwjjkxqtpphycxy'
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True



