# Generated by Django 5.1.1 on 2024-09-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneswitcher', '0003_userpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STRIPE_SECRET_KEY', models.CharField(max_length=255)),
                ('STRIPE_WEBHOOK_SECRET', models.CharField(max_length=255)),
                ('STRIPE_REDIRECT_DOMAIN', models.URLField(default='http://0.0.0.0:8000')),
            ],
            options={
                'verbose_name': 'Stripe Configuration',
                'verbose_name_plural': 'Stripe Configurations',
            },
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
