# Generated by Django 5.1.2 on 2024-10-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneswitcher', '0004_stripeconfig_alter_userpayment_stripe_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='subscription_item_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
