# Generated by Django 5.1.2 on 2024-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneswitcher', '0006_customcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='checkout_session_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
