# Generated by Django 5.1.2 on 2024-10-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sceneswitcher', '0007_userpayment_checkout_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='checkout_session_id',
            new_name='stripe_customer_id',
        ),
    ]
