# Generated by Django 5.1.2 on 2024-10-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceneswitcher', '0008_rename_checkout_session_id_userpayment_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
